name: Chromatic
on: [pull_request]

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: yarn

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
