name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
      NEXT_PUBLIC_SENTRY_DNS: ${{ secrets.NEXT_PUBLIC_SENTRY_DNS }}
      NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - uses: pnpm/action-setup@v4.0.0
        name: Install pnpm
        id: pnpm-install
        with:
          version: 9.13.2
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4.2.0
        with:
          cache: 'pnpm'
          node-version: 20.x

      - name: Install dependencies
        run: pnpm i --no-frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Typecheck
        run: pnpm typecheck

      - name: Find unused exports
        run: pnpm find-deadcode

      - name: Linting
        run: pnpm lint

      - name: Test
        run: pnpm test:ci

      - name: Storybook
        run: pnpm build-storybook
