name: Codecov

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.3.0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - uses: pnpm/action-setup@v2.2.4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8.6.0
          run_install: false

      - name: Install dependencies
        run: pnpm i --no-frozen-lockfile

      - name: Test
        run: pnpm test:ci

      - name: Codecov
        uses: codecov/codecov-action@v3
