name: Release

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed
    branches:
      - main

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Create a new release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - uses: pnpm/action-setup@v4.0.0
        name: Install pnpm
        id: pnpm-install
        with:
          version: 9.13.2
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4.2.0
        with:
          cache: 'pnpm'
          node-version: 20.x

      - name: Install dependencies
        run: HUSKY=0 pnpm i --no-frozen-lockfile

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: HUSKY=0 pnpm release
